//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESF_kz.LocalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="esf", ConfigurationName="LocalService.LocalService")]
    public interface LocalService {
        
        // CODEGEN: Generating message contract since the operation signIdWithReasonList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        ESF_kz.LocalService.signIdWithReasonListResponse signIdWithReasonList(ESF_kz.LocalService.signIdWithReasonList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESF_kz.LocalService.signIdWithReasonListResponse> signIdWithReasonListAsync(ESF_kz.LocalService.signIdWithReasonList request);
        
        // CODEGEN: Generating message contract since the operation generateDocumentSignature is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        ESF_kz.LocalService.generateDocumentSignatureResponse generateDocumentSignature(ESF_kz.LocalService.generateDocumentSignature request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESF_kz.LocalService.generateDocumentSignatureResponse> generateDocumentSignatureAsync(ESF_kz.LocalService.generateDocumentSignature request);
        
        // CODEGEN: Generating message contract since the operation signIdList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        ESF_kz.LocalService.signIdListResponse signIdList(ESF_kz.LocalService.signIdList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESF_kz.LocalService.signIdListResponse> signIdListAsync(ESF_kz.LocalService.signIdList request);
        
        // CODEGEN: Generating message contract since the operation generateSignature is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoiceHash[]))]
        ESF_kz.LocalService.generateSignatureResponse generateSignature(ESF_kz.LocalService.generateSignature request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESF_kz.LocalService.generateSignatureResponse> generateSignatureAsync(ESF_kz.LocalService.generateSignature request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class ListWithReasonSignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InvoiceIdWithReason[] idsWithReasonsField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("idWithReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InvoiceIdWithReason[] idsWithReasons {
            get {
                return this.idsWithReasonsField;
            }
            set {
                this.idsWithReasonsField = value;
                this.RaisePropertyChanged("idsWithReasons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class InvoiceIdWithReason : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class invoiceHash : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hashField;
        
        private string invoiceNumField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string invoiceNum {
            get {
                return this.invoiceNumField;
            }
            set {
                this.invoiceNumField = value;
                this.RaisePropertyChanged("invoiceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class SignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private invoiceHash[] invoiceHashListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public invoiceHash[] invoiceHashList {
            get {
                return this.invoiceHashListField;
            }
            set {
                this.invoiceHashListField = value;
                this.RaisePropertyChanged("invoiceHashList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class SignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] invoiceBodiesField;
        
        private string versionField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("invoiceBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] invoiceBodies {
            get {
                return this.invoiceBodiesField;
            }
            set {
                this.invoiceBodiesField = value;
                this.RaisePropertyChanged("invoiceBodies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class ListSignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] idsField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public long[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
                this.RaisePropertyChanged("ids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class DocumentSignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signedDataField;
        
        private string signatureField;
        
        private string certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signedData {
            get {
                return this.signedDataField;
            }
            set {
                this.signedDataField = value;
                this.RaisePropertyChanged("signedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
                this.RaisePropertyChanged("certificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class DocumentSignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signableDataField;
        
        private string certificatePathField;
        
        private string certificatePinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signableData {
            get {
                return this.signableDataField;
            }
            set {
                this.signableDataField = value;
                this.RaisePropertyChanged("signableData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificatePath {
            get {
                return this.certificatePathField;
            }
            set {
                this.certificatePathField = value;
                this.RaisePropertyChanged("certificatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificatePin {
            get {
                return this.certificatePinField;
            }
            set {
                this.certificatePinField = value;
                this.RaisePropertyChanged("certificatePin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="esf")]
    public partial class ListSignatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signatureField;
        
        private string hashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdWithReasonList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.ListWithReasonSignatureRequest idWithReasonListRequest;
        
        public signIdWithReasonList() {
        }
        
        public signIdWithReasonList(ESF_kz.LocalService.ListWithReasonSignatureRequest idWithReasonListRequest) {
            this.idWithReasonListRequest = idWithReasonListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdWithReasonListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.ListSignatureResponse listSignatureResponse;
        
        public signIdWithReasonListResponse() {
        }
        
        public signIdWithReasonListResponse(ESF_kz.LocalService.ListSignatureResponse listSignatureResponse) {
            this.listSignatureResponse = listSignatureResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateDocumentSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.DocumentSignatureRequest documentSignatureRequest;
        
        public generateDocumentSignature() {
        }
        
        public generateDocumentSignature(ESF_kz.LocalService.DocumentSignatureRequest documentSignatureRequest) {
            this.documentSignatureRequest = documentSignatureRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateDocumentSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.DocumentSignatureResponse documentSignatureResponse;
        
        public generateDocumentSignatureResponse() {
        }
        
        public generateDocumentSignatureResponse(ESF_kz.LocalService.DocumentSignatureResponse documentSignatureResponse) {
            this.documentSignatureResponse = documentSignatureResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.ListSignatureRequest idListRequest;
        
        public signIdList() {
        }
        
        public signIdList(ESF_kz.LocalService.ListSignatureRequest idListRequest) {
            this.idListRequest = idListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.ListSignatureResponse listSignatureResponse;
        
        public signIdListResponse() {
        }
        
        public signIdListResponse(ESF_kz.LocalService.ListSignatureResponse listSignatureResponse) {
            this.listSignatureResponse = listSignatureResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateSignature {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.SignatureRequest signatureRequest;
        
        public generateSignature() {
        }
        
        public generateSignature(ESF_kz.LocalService.SignatureRequest signatureRequest) {
            this.signatureRequest = signatureRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="esf", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ESF_kz.LocalService.SignatureResponse signatureResponse;
        
        public generateSignatureResponse() {
        }
        
        public generateSignatureResponse(ESF_kz.LocalService.SignatureResponse signatureResponse) {
            this.signatureResponse = signatureResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocalServiceChannel : ESF_kz.LocalService.LocalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalServiceClient : System.ServiceModel.ClientBase<ESF_kz.LocalService.LocalService>, ESF_kz.LocalService.LocalService {
        
        public LocalServiceClient() {
        }
        
        public LocalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESF_kz.LocalService.signIdWithReasonListResponse ESF_kz.LocalService.LocalService.signIdWithReasonList(ESF_kz.LocalService.signIdWithReasonList request) {
            return base.Channel.signIdWithReasonList(request);
        }
        
        public ESF_kz.LocalService.ListSignatureResponse signIdWithReasonList(ESF_kz.LocalService.ListWithReasonSignatureRequest idWithReasonListRequest) {
            ESF_kz.LocalService.signIdWithReasonList inValue = new ESF_kz.LocalService.signIdWithReasonList();
            inValue.idWithReasonListRequest = idWithReasonListRequest;
            ESF_kz.LocalService.signIdWithReasonListResponse retVal = ((ESF_kz.LocalService.LocalService)(this)).signIdWithReasonList(inValue);
            return retVal.listSignatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESF_kz.LocalService.signIdWithReasonListResponse> ESF_kz.LocalService.LocalService.signIdWithReasonListAsync(ESF_kz.LocalService.signIdWithReasonList request) {
            return base.Channel.signIdWithReasonListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESF_kz.LocalService.signIdWithReasonListResponse> signIdWithReasonListAsync(ESF_kz.LocalService.ListWithReasonSignatureRequest idWithReasonListRequest) {
            ESF_kz.LocalService.signIdWithReasonList inValue = new ESF_kz.LocalService.signIdWithReasonList();
            inValue.idWithReasonListRequest = idWithReasonListRequest;
            return ((ESF_kz.LocalService.LocalService)(this)).signIdWithReasonListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESF_kz.LocalService.generateDocumentSignatureResponse ESF_kz.LocalService.LocalService.generateDocumentSignature(ESF_kz.LocalService.generateDocumentSignature request) {
            return base.Channel.generateDocumentSignature(request);
        }
        
        public ESF_kz.LocalService.DocumentSignatureResponse generateDocumentSignature(ESF_kz.LocalService.DocumentSignatureRequest documentSignatureRequest) {
            ESF_kz.LocalService.generateDocumentSignature inValue = new ESF_kz.LocalService.generateDocumentSignature();
            inValue.documentSignatureRequest = documentSignatureRequest;
            ESF_kz.LocalService.generateDocumentSignatureResponse retVal = ((ESF_kz.LocalService.LocalService)(this)).generateDocumentSignature(inValue);
            return retVal.documentSignatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESF_kz.LocalService.generateDocumentSignatureResponse> ESF_kz.LocalService.LocalService.generateDocumentSignatureAsync(ESF_kz.LocalService.generateDocumentSignature request) {
            return base.Channel.generateDocumentSignatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESF_kz.LocalService.generateDocumentSignatureResponse> generateDocumentSignatureAsync(ESF_kz.LocalService.DocumentSignatureRequest documentSignatureRequest) {
            ESF_kz.LocalService.generateDocumentSignature inValue = new ESF_kz.LocalService.generateDocumentSignature();
            inValue.documentSignatureRequest = documentSignatureRequest;
            return ((ESF_kz.LocalService.LocalService)(this)).generateDocumentSignatureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESF_kz.LocalService.signIdListResponse ESF_kz.LocalService.LocalService.signIdList(ESF_kz.LocalService.signIdList request) {
            return base.Channel.signIdList(request);
        }
        
        public ESF_kz.LocalService.ListSignatureResponse signIdList(ESF_kz.LocalService.ListSignatureRequest idListRequest) {
            ESF_kz.LocalService.signIdList inValue = new ESF_kz.LocalService.signIdList();
            inValue.idListRequest = idListRequest;
            ESF_kz.LocalService.signIdListResponse retVal = ((ESF_kz.LocalService.LocalService)(this)).signIdList(inValue);
            return retVal.listSignatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESF_kz.LocalService.signIdListResponse> ESF_kz.LocalService.LocalService.signIdListAsync(ESF_kz.LocalService.signIdList request) {
            return base.Channel.signIdListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESF_kz.LocalService.signIdListResponse> signIdListAsync(ESF_kz.LocalService.ListSignatureRequest idListRequest) {
            ESF_kz.LocalService.signIdList inValue = new ESF_kz.LocalService.signIdList();
            inValue.idListRequest = idListRequest;
            return ((ESF_kz.LocalService.LocalService)(this)).signIdListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESF_kz.LocalService.generateSignatureResponse ESF_kz.LocalService.LocalService.generateSignature(ESF_kz.LocalService.generateSignature request) {
            return base.Channel.generateSignature(request);
        }
        
        public ESF_kz.LocalService.SignatureResponse generateSignature(ESF_kz.LocalService.SignatureRequest signatureRequest) {
            ESF_kz.LocalService.generateSignature inValue = new ESF_kz.LocalService.generateSignature();
            inValue.signatureRequest = signatureRequest;
            ESF_kz.LocalService.generateSignatureResponse retVal = ((ESF_kz.LocalService.LocalService)(this)).generateSignature(inValue);
            return retVal.signatureResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESF_kz.LocalService.generateSignatureResponse> ESF_kz.LocalService.LocalService.generateSignatureAsync(ESF_kz.LocalService.generateSignature request) {
            return base.Channel.generateSignatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESF_kz.LocalService.generateSignatureResponse> generateSignatureAsync(ESF_kz.LocalService.SignatureRequest signatureRequest) {
            ESF_kz.LocalService.generateSignature inValue = new ESF_kz.LocalService.generateSignature();
            inValue.signatureRequest = signatureRequest;
            return ((ESF_kz.LocalService.LocalService)(this)).generateSignatureAsync(inValue);
        }
    }
}
