// <auto-generated/>
// Türkçe: Global bastırmalar — PROJENİN İHTİYACINA GÖRE sınırlı tutun.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0065:Misplaced using directive", Justification = "Solution-wide style", Scope = "module")]
